[package]
name = "mcr-bench"
version = "0.1.0"
edition = "2024"

[dev-dependencies]
criterion = "0.8"

[dependencies]
zopfli = "^0.8.0"
flate2 = "^1.0.26"

[[bench]]
name = "compress"
harness = false

[[bench]]
name = "brackets"
harness = false
